### PR TITLE
qvm-wireguard qubename user input

### PR DESCRIPTION
**Pull request by n1ete**
just a tiny change to make qvm-wireguard work with multiple wireguard qubes

### CODE REVIEW

**Comment by ben-grande** [comment]
Hello, thanks for the contribution.

However, it already works with multiple qubes. The expansion `${1:-"default_value"}` is a shell expansion, if `$1` is not set or empty, use `default_value` instead, else use `$1`. I should have done a usage message to explain that the default qube is the one provided by qusal (sys-wireguard), but you can use with any other wireguard qube.

Read [GNU Bash Shell Parameter Expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) for more information, although it applies to Bourne Shell, Ksh and Zsh and many others, so it is widely supported, not only Bash.

If you understood the above and wants to contribute a usage message, I can accept that, use [git-init-qrexec](https://github.com/ben-grande/qusal/blob/c6dbccfe24fbf7a4a602b6ca309c65ead8f84ba7/salt/sys-git/files/client/git-core/git-init-qrexec#L15) usage message as template.

**Comment by ben-grande** [comment]
Note: Your commits do not follow the format required for [contribution](https://github.com/ben-grande/qusal/blob/main/docs/CONTRIBUTING.md), if you run gitlint and pre-commit locally you will see, for now, the linting is not working for PRs.

**Comment by n1ete** [comment]
Thanks for the explanation, learned something new and i will close that pull request then for now, i made a sys-mitmproxy saltstate, will need to lint and cleanup the scripts, but i will do a new pull request and close this one for now.

**Comment by ben-grande** [comment]
> I made a sys-mitmproxy saltstate will need to lint and cleanup the scripts, but i will do a new pull request and close this one for now then... :)

If you plan to contribute a new formula such as sys-mitmproxy, please open an issue first to discuss it, this makes sure you don't waste time in case it is not accepted.

**Pull request closed without merging**
